# Generated by Django 2.0.7 on 2018-12-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test',
            new_name='test_field',
        ),
    ]
