# Generated by Django 2.0.7 on 2018-12-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_auto_20181211_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Org',
        ),
    ]
