# Generated by Django 2.0.7 on 2018-09-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensornotification',
            name='max_optimal_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensornotification',
            name='min_optimal_value',
            field=models.FloatField(null=True),
        ),
    ]
